series: Intermediate C++
title: Bitwise Operators
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Bitwise operators can be used to manipulate individual bits in your data.
language: C++
tags:
  - Core
extra_resources:
  - link: http://www.cplusplus.com/doc/tutorial/variables/
    title: More Information about C++ data types.
connections:
  - series: Basic C++
    title: Functions
  - series: Basic C++
    title: Casting Data